<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjVa1mE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjVa1mE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVjVa1mE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVjVa1mE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVjVa1mE\App_KernelDevDebugContainer([
    'container.build_hash' => 'VjVa1mE',
    'container.build_id' => 'b8d5f5c1',
    'container.build_time' => 1650010996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjVa1mE');
